### ISSUE TITLE
Improper Licensing

### ISSUE THREAD

**Issue by rushsteve1** [rcos/rcos-branding#9]
The `LICENSE` file included with this project is the MIT license, which only applies to source code, and not to artistic works such as the various images in this repo.

I suggest adding an additional `COPYING` file containing an appropriate license.

I opened this issue in order to discuss what that license should be. I am in favor of the Creative Commons Attribution 4.0 International (CC-BY-4.0) but I invite any further ideas.

**Comment by Alfriadox** [comment]
I know this issue is like a year old but I'm using parts of this repo in Telesocpe and yes, I believe CC-BY-4.0 would be appropriate.
